required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
]

[prune]
  go-tests = true
  unused-packages = true
  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  revision = "v1.11.2"

[[constraint]]
  name = "k8s.io/api"
  revision = "kubernetes-1.11.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "kubernetes-1.11.2"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "kubernetes-1.11.2"

[[constraint]]
  name = "k8s.io/apiserver"
  revision = "kubernetes-1.11.2"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.2"
